# Generated by Django 3.2 on 2021-08-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment_likes_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='dislikes_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='likes_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
