# Generated by Django 3.2 on 2021-08-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210805_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='dislikes_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='likes_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
